### ISSUE TITLE
Autoresponder

### ISSUE THREAD

**Issue by srakl** [yeriepiscesa/cf7-send-wa#2]
Is there a way to auto respond through whatsapp? If someone subscribes to my website using contact form 7 (name, email and number), i send them "thank you" message through whastapp?

**Comment by yeriepiscesa** [comment]
Yes, you can set in the whatsapp tab. but only work if you're using 3rd party service. 

For 3rd party services, currently suppot for Twilio and some unofficial Indonesia's WhatsApp gateway (Fonnte, RuangWA & WABlas).

![Screen-Shot-2020-06-10-at-20 25 37](https://user-images.githubusercontent.com/8475492/90786501-d41e2400-e32d-11ea-90d0-08dd8521275b.png)

![Screen-Shot-2020-06-08-at-19 36 48](https://user-images.githubusercontent.com/8475492/90787650-2744a680-e32f-11ea-8322-a5374709ea99.png)

**Comment by srakl** [comment]
Ah nice! so only with 3rd party? Can't do direct right?

**Comment by yeriepiscesa** [comment]
That's right, since the default behavior (literally) just send WA link which need to be triggered by user for sending, it will be very weird if user send for himself.
However, you could write your own code using any API (beyond the 3rd parties I've listed) by hooking to cf7sendwa_custom_send_api hook. See the example here https://gist.github.com/yeriepiscesa/373ac024b04ac9cbcb55ac732f3ec704
